@baseURL = http://localhost:3333
@access_token = {{authenticate.response.body.access_token}}
@taskId = {{create_task.response.body.task.id}}


# @name create_user
POST {{baseURL}}/users
Content-Type: application/json

{
  "confirmPassword": "12345678",
  "password": "12345678",
  "username": "John Doe"
}

###

# @name authenticate
POST {{baseURL}}/auth
Content-Type: application/json

{
  "password": "12345678",
  "username": "John Doe"
}

###

# @name create_task
POST {{baseURL}}/tasks
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "description": "Testando descrição",
  "title": "Simple title"
}

###

# @name fetch_tasks
GET {{baseURL}}/tasks?page=1
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# @name delete_task
DELETE {{baseURL}}/tasks/6cf254f1-e6ae-4df7-a99d-77a27bd7a0ae
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# @name update_task
PUT {{baseURL}}/tasks/6cf254f1-e6ae-4df7-a99d-77a27bd7a0ae
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "description": "Updated simple description",
  "status": true,
  "title": "Updated simple Title"
}
